site_name: interfacer
nav:
    - Home: index.md
    - Protocols: protocol.md
    - Reference:
        - Module: module-reference.md
        - Generate: generate-reference.md
        - Identify: identify-reference.md
        - Interface: interface-reference.md
    - Citation: citation.md
theme: 
  name: material
  icon:
    logo: material/bookmark
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: red
      toggle:
        icon: material/weather-sunny
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: red
      toggle:
        icon: material/weather-night
        name: Switch to light mode
plugins:
    - search
    - bibtex:
        bib_file: "docs/refs.bib"
        cite_style: "plain"
    - mkdocstrings
markdown_extensions:
    - markdown_wavedrom
    - pymdownx.details
    - pymdownx.superfences
    - admonition
extra_javascript:
    - https://cdnjs.cloudflare.com/ajax/libs/wavedrom/2.6.8/wavedrom.min.js
    - https://cdnjs.cloudflare.com/ajax/libs/wavedrom/2.6.8/skins/default.js
    - js/wavedrom_loader.js