/*
* Module: top
* File:   out_wrapper.v
* Date:   22:55 26/09/2020
* Type:   wrapper
* DO NOT MODIFY THIS FILE; AUTOMATICALLY GENERATED BY INTERFACER
*/

module top_wrapper
(
  (* X_INTERFACE_INFO = "xilinx.com:signal:clock:1.0 CLK CLK" *)
  input wire CLK,
  (* X_INTERFACE_INFO = "xilinx.com:signal:reset:1.0 RST RST" *)
  input wire RST,
  input wire enable,
  input wire [16:0] value,
  output wire [7:0] led
);


  top
  blackbox
  (
    .CLK(CLK),
    .RST(RST),
    .enable(enable),
    .value(value),
    .led(led)
  );


endmodule
