/*
* Module: top
* File:   out_blackbox.v
* Date:   22:55 26/09/2020
* Type:   blackbox
* DO NOT MODIFY THIS FILE; AUTOMATICALLY GENERATED BY INTERFACER
*/

module top
(
  input [0:0] CLK,
  input [0:0] RST,
  input [0:0] enable,
  input [16:0] value,
  output [7:0] led
);


endmodule
