/*
* Module: zycap
* File:   rtl/.inst/top_v1_blackbox.v
* Date:   01:09 13/10/2020
* Type:   blackbox
* DO NOT MODIFY THIS FILE; AUTOMATICALLY GENERATED BY INTERFACER
*/

module blackbox_1
(
  input [0:0] CLK,
  input [0:0] RST,
  input [0:0] toot,
  input [0:0] enable,
  input [16:0] value,
  output [7:0] led
);


endmodule
