/*
* Module: zycap
* File:   rtl/.inst/_wrapper.v
* Date:   01:09 13/10/2020
* Type:   wrapper
* DO NOT MODIFY THIS FILE; AUTOMATICALLY GENERATED BY INTERFACER
*/

module pr_wrapper
(
  (* X_INTERFACE_INFO = "xilinx.com:signal:clock:1.0 CLK_0 CLK" *)
  input wire CLK_0,
  (* X_INTERFACE_INFO = "xilinx.com:signal:reset:1.0 RST_0 RST" *)
  input wire RST_0,
  input wire toot_0,
  (* X_INTERFACE_INFO = "xilinx.com:signal:clockenable:1.0 enable_0 CE" *)
  input wire enable_0,
  input wire [16:0] value_0,
  output wire [7:0] led_0,
  (* X_INTERFACE_INFO = "xilinx.com:signal:clock:1.0 CLK_1 CLK" *)
  input wire CLK_1,
  (* X_INTERFACE_INFO = "xilinx.com:signal:reset:1.0 RST_1 RST" *)
  input wire RST_1,
  input wire toot_1,
  (* X_INTERFACE_INFO = "xilinx.com:signal:clockenable:1.0 enable_1 CE" *)
  input wire enable_1,
  input wire [16:0] value_1,
  output wire [7:0] led_1
);


  (* black_box *)
  blackbox_0
  inst_0
  (
    .CLK(CLK_0),
    .RST(RST_0),
    .toot(toot_0),
    .enable(enable_0),
    .value(value_0),
    .led(led_0)
  );


  (* black_box *)
  blackbox_1
  inst_1
  (
    .CLK(CLK_1),
    .RST(RST_1),
    .toot(toot_1),
    .enable(enable_1),
    .value(value_1),
    .led(led_1)
  );


endmodule
