name: Docs
on:
  push:
    branches: 
      - master
      - main
jobs:
  docs:
    runs-on: ubuntu-latest
    name: Builds docs for GH pages
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material mkdocs-wavedrom-plugin mkdocs-bibtex
      - run: mkdocs gh-deploy --force
